"use strict";
const crypto = require("crypto");
const express = require("express");
const { rateLimit } = require("express-rate-limit");
const { getPool } = require("../lib/db");
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const ORIGINS=new Set(["https://cafe-test.kotocafe.ru","https://cats-test.kotocafe.ru"]);
const hash=(v,s)=>crypto.createHash("sha256").update(String(v)+s).digest("hex");
function parseCookie(header,name){for(const p of String(header||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===name)return decodeURIComponent(p.slice(i+1).trim())}return null}
function createMediaLikesRouter(options={}){
 const pool=options.pool||getPool(),secret=options.secret===undefined?process.env.MEDIA_LIKES_SECRET:options.secret,logger=options.logger||console,limits=options.rateLimits||{};
 const router=express.Router(), configured=typeof secret==="string"&&secret.length>=32;
 const badConfig=(req,res,next)=>configured?next():res.status(503).json({ok:false,error:"media_likes_not_configured"});
 const ensureMediaVisitor=(req,res,next)=>{const raw=parseCookie(req.headers.cookie,"koto_media_visitor"),[id,sig,...rest]=String(raw||"").split(".");let valid=rest.length===0&&UUID.test(id||"")&&/^[a-f0-9]{64}$/i.test(sig||"");if(valid){const a=Buffer.from(sig,"hex"),b=Buffer.from(crypto.createHmac("sha256",secret).update(id).digest("hex"),"hex");valid=a.length===b.length&&crypto.timingSafeEqual(a,b)}const value=valid?id:crypto.randomUUID();if(!valid)res.cookie("koto_media_visitor",value+"."+crypto.createHmac("sha256",secret).update(value).digest("hex"),{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:31536000000});req.mediaVisitor={id:value,visitorHash:hash(value,secret)};next()};
 const hashes=(req,res,next)=>{req.mediaLikeIpHash=hash(req.ip||"",secret);req.mediaLikeUserAgentHash=hash(req.headers["user-agent"]||"",secret);next()};
 const origin=(req,res,next)=>{const o=String(req.headers.origin||"");if(!ORIGINS.has(o)){logger.warn("media_like_invalid_origin");return res.status(403).json({ok:false,error:"invalid_origin"})}res.set({"Access-Control-Allow-Origin":o,"Access-Control-Allow-Credentials":"true",Vary:"Origin"});next()};
 const limiter=(windowMs,max,keyGenerator)=>rateLimit({windowMs,max,keyGenerator,legacyHeaders:false,standardHeaders:false,handler:(req,res)=>{logger.warn("media_like_rate_limited",{visitor_hash:req.mediaVisitor.visitorHash.slice(0,8),ip_hash:req.mediaLikeIpHash.slice(0,8)});res.status(429).json({ok:false,error:"rate_limited"})}});
 const mutate=[badConfig,ensureMediaVisitor,hashes,origin,limiter(60000,limits.visitorMinute||20,r=>r.mediaVisitor.visitorHash),limiter(3600000,limits.visitorHour||100,r=>r.mediaVisitor.visitorHash),limiter(60000,limits.ipMinute||60,r=>r.mediaLikeIpHash),limiter(3600000,limits.ipHour||300,r=>r.mediaLikeIpHash)];
 async function media(id){return (await pool.query("SELECT id FROM public.cafe_media WHERE id=$1 AND status='published'",[id])).rowCount>0}
 router.get("/",badConfig,ensureMediaVisitor,async(req,res)=>{try{const ids=[...new Set(String(req.query.media_ids||"").split(",").map(x=>x.trim()).filter(Boolean))];if(!ids.length||ids.length>100||ids.some(x=>!UUID.test(x)))return res.status(400).json({ok:false,error:"invalid_media_ids"});const q=await pool.query("WITH visible AS (SELECT id FROM public.cafe_media WHERE id=ANY($1::uuid[]) AND status='published'), counts AS (SELECT media_id,count(*)::int count FROM public.cafe_media_likes WHERE media_id IN (SELECT id FROM visible) GROUP BY media_id), mine AS (SELECT media_id FROM public.cafe_media_likes WHERE media_id IN (SELECT id FROM visible) AND visitor_hash=$2) SELECT visible.id,coalesce(counts.count,0) count,(mine.media_id IS NOT NULL) liked FROM visible LEFT JOIN counts ON counts.media_id=visible.id LEFT JOIN mine ON mine.media_id=visible.id",[ids,req.mediaVisitor.visitorHash]);const items={};q.rows.forEach(x=>items[x.id]={count:Number(x.count),liked:Boolean(x.liked)});res.json({ok:true,items})}catch(e){logger.error("media_like_database_error");res.status(500).json({ok:false,error:"database_error"})}});
 async function change(req,res,liked){try{const id=req.params.mediaId;if(!UUID.test(id))return res.status(400).json({ok:false,error:"invalid_media_id"});if(!await media(id))return res.status(404).json({ok:false,error:"media_not_found"});await pool.query("BEGIN");try{if(liked)await pool.query("INSERT INTO public.cafe_media_likes (media_id,visitor_hash,ip_hash,user_agent_hash) VALUES ($1,$2,$3,$4) ON CONFLICT (media_id,visitor_hash) DO NOTHING",[id,req.mediaVisitor.visitorHash,req.mediaLikeIpHash,req.mediaLikeUserAgentHash]);else await pool.query("DELETE FROM public.cafe_media_likes WHERE media_id=$1 AND visitor_hash=$2",[id,req.mediaVisitor.visitorHash]);const c=await pool.query("SELECT count(*)::int count FROM public.cafe_media_likes WHERE media_id=$1",[id]);await pool.query("COMMIT");logger.info(liked?"media_like_added":"media_like_removed",{media_id:id,visitor_hash:req.mediaVisitor.visitorHash.slice(0,8),ip_hash:req.mediaLikeIpHash.slice(0,8)});res.json({ok:true,count:Number(c.rows[0].count),liked})}catch(e){await pool.query("ROLLBACK");throw e}}catch(e){logger.error("media_like_database_error");res.status(500).json({ok:false,error:"database_error"})}}
 router.put("/:mediaId",...mutate,(req,res)=>change(req,res,true));router.delete("/:mediaId",...mutate,(req,res)=>change(req,res,false));return router;
}
const router=createMediaLikesRouter();module.exports=router;module.exports.createMediaLikesRouter=createMediaLikesRouter;
