"use strict";
const fs = require("fs"); const fsp = fs.promises; const path = require("path"); const crypto = require("crypto");
const ROOT = path.resolve(__dirname, ".."); const DEFAULT_FILE = path.join(ROOT, "data/partners.json"); const DEFAULT_BACKUPS = path.join(ROOT, "data/backups");
const ID = /^[a-z0-9][a-z0-9-]{0,95}$/; const CONTROL = /[\u0000-\u001f\u007f]/;
const FIELDS = new Set(["slug","name","logo","type","featured","showOnPartnersPage","showMini","priority","description","url","active","show_on_foundation","show_on_cafe"]);
function fail(code){const e=new Error(code);e.code=code;return e} function clone(x){return JSON.parse(JSON.stringify(x))}
function validPartnerId(id){return typeof id==="string"&&id===id.trim()&&ID.test(id)&&!id.includes("..")&&!id.includes("/")&&!id.includes("\\")}
function existing(p){if(!p||Array.isArray(p)||typeof p!=="object"||(p.slug!==undefined&&!validPartnerId(p.slug)))throw fail("invalid_existing_partner"); for(const k of ["name","logo","type","description","url"])if(p[k]!==undefined&&(typeof p[k]!=="string"||CONTROL.test(p[k])))throw fail("invalid_existing_partner"); for(const k of ["featured","showOnPartnersPage","showMini","active","show_on_foundation","show_on_cafe"])if(p[k]!==undefined&&typeof p[k]!=="boolean")throw fail("invalid_existing_partner"); if(p.priority!==undefined&&(typeof p.priority!=="number"||!Number.isFinite(p.priority)))throw fail("invalid_existing_partner")}
function input(data,{creating=false}={}){if(!data||Array.isArray(data)||typeof data!=="object")throw fail("invalid_partner");for(const k of Object.keys(data))if(!FIELDS.has(k))throw fail("unknown_field");if((creating&&!validPartnerId(data.slug))||(data.slug!==undefined&&!validPartnerId(data.slug)))throw fail("invalid_id");for(const k of ["name","type","description"])if(data[k]!==undefined&&(typeof data[k]!=="string"||CONTROL.test(data[k])||(k==="name"&&!data[k].trim())))throw fail("invalid_"+k);if(creating&&data.name===undefined)throw fail("invalid_name");if(data.logo!==undefined&&(typeof data.logo!=="string"||!data.logo.startsWith("/images/partners/")||data.logo.includes("..")||data.logo.includes("\\")||CONTROL.test(data.logo)||/\.svg(?:$|[?#])/i.test(data.logo)))throw fail("invalid_logo");if(creating&&data.logo===undefined)throw fail("invalid_logo");if(data.url!==undefined){try{const u=new URL(data.url);if(!["http:","https:"].includes(u.protocol))throw 0}catch(_){throw fail("invalid_url")}}if(creating&&data.url===undefined)throw fail("invalid_url");for(const k of ["featured","showOnPartnersPage","showMini","active","show_on_foundation","show_on_cafe"])if(data[k]!==undefined&&typeof data[k]!=="boolean")throw fail("invalid_"+k);if(data.priority!==undefined&&(typeof data.priority!=="number"||!Number.isFinite(data.priority)))throw fail("invalid_priority");return clone(data)}
async function sync(file){const h=await fsp.open(file,"r");try{await h.sync()}finally{await h.close()}}
function createPartnersStore({partnersFile=DEFAULT_FILE,backupsDir=DEFAULT_BACKUPS,invalidateCache=()=>{}}={}){const file=path.resolve(partnersFile), backupDir=path.resolve(backupsDir);let q=Promise.resolve();async function read(){let x;try{x=JSON.parse(await fsp.readFile(file,"utf8"))}catch(e){throw fail(e.code==="ENOENT"?"partners_file_missing":"invalid_partners_json")}if(!Array.isArray(x))throw fail("invalid_partners_root");x.forEach(existing);return x}function queued(fn){const out=q.then(fn,fn);q=out.catch(()=>{});return out}async function write(before,next){await fsp.mkdir(backupDir,{recursive:true});const bak=path.join(backupDir,"partners-"+Date.now()+"-"+crypto.randomUUID()+".json");await fsp.writeFile(bak,JSON.stringify(before,null,2)+"\n",{flag:"wx",mode:0o600});await sync(bak);const tmp=path.join(path.dirname(file),"."+path.basename(file)+"."+crypto.randomUUID()+".tmp");try{await fsp.writeFile(tmp,JSON.stringify(next,null,2)+"\n",{flag:"wx",mode:0o600});await sync(tmp);await fsp.rename(tmp,file);try{const d=await fsp.open(path.dirname(file),"r");try{await d.sync()}finally{await d.close()}}catch(_){};invalidateCache()}catch(e){await fsp.unlink(tmp).catch(()=>{});throw e}}async function mutate(fn){return queued(async()=>{const before=await read(),next=await fn(clone(before));next.forEach(existing);await write(before,next);return clone(next)})}return {listPartners:async()=>clone(await read()),getPartnerById:async id=>{if(!validPartnerId(id))throw fail("invalid_id");return clone((await read()).find(x=>x.slug===id)||null)},validatePartner:input,createPartner:async data=>{const x=input(data,{creating:true});await mutate(a=>{if(a.some(y=>y.slug===x.slug))throw fail("duplicate_id");a.push(x);return a});return x},updatePartner:async(id,data)=>{if(!validPartnerId(id)||(data&&data.slug!==undefined&&data.slug!==id))throw fail("invalid_id");const p=input(data||{});await mutate(a=>{const i=a.findIndex(x=>x.slug===id);if(i<0)throw fail("partner_not_found");a[i]={...a[i],...p,slug:id};return a});return clone((await read()).find(x=>x.slug===id))},deletePartner:async id=>{if(!validPartnerId(id))throw fail("invalid_id");await mutate(a=>{const i=a.findIndex(x=>x.slug===id);if(i<0)throw fail("partner_not_found");a.splice(i,1);return a})},reorderPartners:async ids=>{if(!Array.isArray(ids)||ids.some(x=>!validPartnerId(x)))throw fail("invalid_reorder");await mutate(a=>{if(ids.length!==a.length||new Set(ids).size!==ids.length)throw fail("invalid_reorder");const m=new Map(a.map(x=>[x.slug,x]));if(ids.some(x=>!m.has(x)))throw fail("invalid_reorder");return ids.map((id,i)=>({...m.get(id),priority:i+1}))})}}}
module.exports={createPartnersStore,partnersStore:createPartnersStore(),validPartnerId};
