"use strict";
const express=require("express"),path=require("path");
const CORE_ROOT=path.resolve(__dirname,"..");
const defaults={...require("./auth"),...require("./csrf"),partnersStore:require("./partners-store").partnersStore,uploader:require("./upload").createPartnerLogoUploader()};
const asyncHandler=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
function createInternalToolsRouter(deps={}){const d={...defaults,...deps},r=express.Router();const auth=d.requireToolAuth,perm=d.requireToolPermission;
 const apiError=(err,req,res,next)=>{const c=err&&err.code||"storage_error",status=c==="duplicate_id"?409:c==="partner_not_found"?404:(err&&err.status===413)||c==="upload_too_large"||c==="entity.too.large"?413:c==="unsupported_image_type"||c==="invalid_image_signature"?415:/^(invalid_|unknown_field)/.test(c)?400:500;res.status(status).json({ok:false,error:{code:c,message:"Не удалось выполнить операцию."}})};
 const page=(name,extra={})=>asyncHandler((req,res)=>res.render(path.join(CORE_ROOT,"views","internal-tools",name),{toolUser:req.toolUser,...extra}));
 r.get("/tools",auth,page("index"));r.get("/tools/media",auth,perm("media"),page("media"));r.get("/tools/partners",auth,perm("partners"),asyncHandler((req,res)=>res.render(path.join(CORE_ROOT,"views","internal-tools","partners"),{toolUser:req.toolUser,csrfToken:d.getOrCreateCsrfToken(req)})));r.get("/tools/avatar-editor",auth,perm("avatars"),(req,res)=>res.redirect(302,"/avatar-editor"));
 const a=express.Router();a.get("/partners",auth,perm("partners"),asyncHandler(async(req,res)=>res.json({ok:true,partners:await d.partnersStore.listPartners()})));const guarded=[auth,perm("partners"),d.requireCsrf];
 a.post("/partners",...guarded,asyncHandler(async(req,res)=>res.status(201).json({ok:true,partner:await d.partnersStore.createPartner(req.body)})));a.put("/partners/order",...guarded,asyncHandler(async(req,res)=>{await d.partnersStore.reorderPartners(req.body&&req.body.ids);res.json({ok:true})}));a.put("/partners/:id",...guarded,asyncHandler(async(req,res)=>res.json({ok:true,partner:await d.partnersStore.updatePartner(req.params.id,req.body)})));a.delete("/partners/:id",...guarded,asyncHandler(async(req,res)=>{await d.partnersStore.deletePartner(req.params.id);res.json({ok:true})}));a.post("/partners/upload-logo",...guarded,express.raw({type:"application/octet-stream",limit:"5mb"}),asyncHandler(async(req,res)=>{const x=await d.uploader.uploadPartnerLogo({partnerId:req.get("x-partner-id"),buffer:req.body});res.status(201).json({ok:true,file:{filename:x.filename,publicUrl:x.publicUrl,mimeType:x.mimeType,size:x.size}})}));a.use(apiError);r.use("/api/tools",a);return r}
module.exports=createInternalToolsRouter();module.exports.createInternalToolsRouter=createInternalToolsRouter;
