"use strict";
const crypto=require("crypto"),createDirectusClient=require("../lib/directus-client"),{verifyInitData}=require("../avatar-editor/services/telegram-auth");
const COOKIE="media_upload_session",TTL=8*60*60*1000,MAX_LOGIN_AGE=600,sessions=new Map();
const cookies=h=>String(h||"").split(";").reduce((o,p)=>{const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim());return o;},{});
const client=()=>createDirectusClient({directusUrl:process.env.DIRECTUS_URL,directusToken:process.env.DIRECTUS_TOKEN});
function issue(res,telegramId){const id=crypto.randomBytes(32).toString("base64url");sessions.set(id,{telegramId,csrf:crypto.randomBytes(32).toString("base64url"),expires:Date.now()+TTL});res.cookie(COOKIE,id,{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:TTL});console.info("media-upload session created");}
function get(req){const id=cookies(req.headers.cookie)[COOKIE],s=id&&sessions.get(id);if(!s||s.expires<Date.now()){if(id)sessions.delete(id);return null;}return{id,...s};}
async function canAccessMediaUploader(telegramId){const r=await client().get("/items/animals_team",{filter:{telegram_id:{_eq:String(telegramId)},is_active:{_eq:true}},fields:"id,full_name,role_id.id,role_id.code,role_id.title",limit:1}),row=Array.isArray(r.data)&&r.data[0];if(!row)return null;const role=row.role_id||{},admin=/\badmin\b|админ|администратор/.test(`${role.code||""} ${role.title||""}`.toLowerCase());if(!admin){const p=await client().get("/items/animals_role_permissions",{filter:{role_id:{_eq:role.id||role}},fields:"permission_id.id",limit:200}),ids=new Set((p.data||[]).map(x=>Number(x.permission_id?.id||x.permission_id)));if(!ids.has(3)&&!ids.has(17))return null;}return{telegramId:Number(telegramId),name:row.full_name||"Сотрудник"};}
async function enter(res,telegramId,json=true){try{const member=await canAccessMediaUploader(telegramId);if(!member)return json?res.status(403).json({ok:false,error:"forbidden",message:"Доступ к загрузке медиа не разрешён."}):res.status(403).send("Недостаточно прав.");issue(res,member.telegramId);return json?res.json({ok:true,user:{name:member.name}}):res.redirect(303,"/media-upload/");}catch(e){console.error("media_upload_access_check_failed",e.message);return json?res.status(503).json({ok:false,error:"access_check_failed",message:"Не удалось проверить доступ."}):res.status(503).send("Не удалось проверить доступ.");}}
async function authenticateMiniApp(req,res){console.info("media-upload miniapp auth started");const user=verifyInitData(req.body?.initData,process.env.TELEGRAM_BOT_TOKEN);if(!user){console.info("media-upload miniapp auth failure");return res.status(401).json({ok:false,error:"unauthorized",message:"Не удалось подтвердить авторизацию Telegram."});}console.info("media-upload miniapp auth success");return enter(res,user.id);}
const authenticate=authenticateMiniApp;
function widgetId(q){const hash=String(q.hash||""),date=Number(q.auth_date),id=String(q.id||"");if(!/^[1-9]\d*$/.test(id)||!Number.isSafeInteger(date)||date>Math.floor(Date.now()/1000)+60||Math.floor(Date.now()/1000)-date>MAX_LOGIN_AGE||!/^[0-9a-f]{64}$/i.test(hash)||!process.env.TELEGRAM_BOT_TOKEN)return null;const data=Object.entries(q).filter(([k])=>k!=="hash").map(([k,v])=>[k,String(v)]).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n"),key=crypto.createHash("sha256").update(process.env.TELEGRAM_BOT_TOKEN).digest(),expected=crypto.createHmac("sha256",key).update(data).digest("hex"),a=Buffer.from(hash,"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&crypto.timingSafeEqual(a,b)?Number(id):null;}
function callback(req,res){console.info("media-upload browser auth callback received");const id=widgetId(req.query);if(!id)return res.status(401).send("Не удалось подтвердить вход Telegram.");console.info("media-upload telegram hash valid");return enter(res,id,false);}
async function authenticateWidget(req,res){const id=widgetId(req.body||{});if(!id)return res.status(401).json({ok:false,error:"unauthorized",message:"Не удалось подтвердить вход Telegram."});console.info("media-upload telegram hash valid");return enter(res,id,true);}
function requireSession(req,res,next){const s=get(req);if(!s)return res.status(401).json({ok:false,error:"unauthorized",message:"Требуется вход через Telegram."});req.mediaUploadUser={telegramId:s.telegramId};req.mediaUploadSession=s;next();}
function csrf(req,res,next){if(req.get("origin")!=="https://apps-test.kotocafe.ru")return res.status(403).json({ok:false,error:"invalid_origin"});const a=Buffer.from(String(req.get("x-csrf-token")||"")),b=Buffer.from(String(req.mediaUploadSession?.csrf||""));if(!a.length||a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(403).json({ok:false,error:"invalid_csrf"});next();}
function status(req,res){return res.status(get(req)?200:401).json({authenticated:Boolean(get(req))});}function token(req,res){res.json({csrfToken:req.mediaUploadSession.csrf});}function logout(req,res){const id=cookies(req.headers.cookie)[COOKIE];if(id)sessions.delete(id);res.clearCookie(COOKIE,{httpOnly:true,secure:true,sameSite:"lax",path:"/"});res.json({ok:true});}
module.exports={authenticate,authenticateMiniApp,authenticateWidget,callback,requireSession,csrf,canAccessMediaUploader,status,token,logout};
