"use strict";

const express = require("express");
const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const crypto = require("crypto");
const { spawn } = require("child_process");
const axios = require("axios");
const sharp = require("sharp");
const FormData = require("form-data");
const store = require("./store");
const { authenticate, authenticateMiniApp, authenticateWidget, callback, requireSession, csrf, status: sessionStatus, token, logout } = require("./auth");
const createDirectusClient = require("../lib/directus-client");
const { generatePosterForMedia } = require("../lib/media/video-posters");

const CHUNK_SIZE = 8 * 1024 * 1024;
const MAX_SIZE = 500 * 1024 * 1024;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const VIDEO_EXTENSIONS = new Set([".mp4", ".mov", ".webm"]);
const active = new Map();

function directus() { return createDirectusClient({ directusUrl: process.env.DIRECTUS_URL, directusToken: process.env.DIRECTUS_TOKEN }); }
function error(res, status, code, message) { return res.status(status).json({ ok: false, error: code, message }); }
function validId(value) { return UUID.test(String(value || "")); }
function safeName(name) { return String(name || "файл").replace(/[\\/\0]/g, "_").slice(0, 180); }
function publicMeta(meta) { const { owner_telegram_id, directus_file_ids, ...safe } = meta; return safe; }
async function owned(req, res) { try { const record = await store.read(req.params.uploadId); if (String(record.metadata.owner_telegram_id) !== String(req.mediaUploadUser.telegramId)) { error(res, 403, "forbidden", "Эта загрузка принадлежит другому пользователю."); return null; } return record; } catch { error(res, 404, "not_found", "Загрузка не найдена."); return null; } }
function run(command, args, timeoutMs = 15 * 60 * 1000) { return new Promise((resolve, reject) => { const child = spawn(command, args, { stdio: ["ignore", "ignore", "pipe"] }); let stderr = ""; const timer = setTimeout(() => { child.kill("SIGKILL"); reject(new Error("process_timeout")); }, timeoutMs); child.stderr.on("data", c => { stderr = (stderr + c).slice(-4000); }); child.on("error", reject); child.on("close", code => { clearTimeout(timer); code === 0 ? resolve(stderr) : reject(new Error(`${command}_failed:${stderr}`)); }); }); }
async function listAnimals(req, res) { try { const result = await directus().get("/items/animals", { fields: "id,name,published,status", sort: "name", limit: 500 }); res.json({ ok: true, data: (result.data || []).map(x => ({ id: x.id, name: x.name, published: Boolean(x.published), status: x.status })) }); } catch (e) { console.error("media_upload_animals_failed", e.message); error(res, 503, "animals_unavailable", "Не удалось получить список кошек."); } }
async function init(req, res) { const body = req.body || {}; const size = Number(body.size); const type = String(body.type || ""); const source = body.source === "" || body.source == null ? null : String(body.source); const isMain = Boolean(body.is_main); if (!validId(body.animal_id) || !Number.isSafeInteger(size) || size < 1 || size > MAX_SIZE || !["photo", "video"].includes(type) || ![null, "street", "kotocafe"].includes(source) || (type === "video" && isMain)) return error(res, 400, "invalid_payload", "Проверьте выбранную кошку, тип и размер файла."); const ext = path.extname(safeName(body.filename)).toLowerCase(); if ((type === "photo" && !IMAGE_TYPES.has(String(body.mime || ""))) || (type === "video" && !VIDEO_EXTENSIONS.has(ext))) return error(res, 415, "unsupported_type", "Этот формат файла не поддерживается."); await store.cleanup(); const existing = [...active.values()].filter(x => x.owner === req.mediaUploadUser.telegramId).length; if (existing >= 2) return error(res, 429, "too_many_uploads", "Дождитесь завершения текущей загрузки."); const now = new Date().toISOString(); const { id, dir } = await store.create({ owner_telegram_id: req.mediaUploadUser.telegramId, display_name: safeName(body.filename), server_name: crypto.randomUUID() + ext, expected_size: size, chunk_size: CHUNK_SIZE, chunk_count: Math.ceil(size / CHUNK_SIZE), received_chunks: [], animal_id: body.animal_id, type, source, is_main: isMain, mime: String(body.mime || ""), status: "created", created_at: now, updated_at: now, error: null, directus_file_ids: [] }); active.set(id, { owner: req.mediaUploadUser.telegramId }); await fsp.writeFile(path.join(dir, ".owner"), String(req.mediaUploadUser.telegramId), { mode: 0o600 }); res.status(201).json({ ok: true, uploadId: id, chunkSize: CHUNK_SIZE, status: "created" }); }
async function status(req, res) { const record = await owned(req, res); if (record) res.json({ ok: true, data: publicMeta(record.metadata) }); }
async function receiveChunk(req, res) { const record = await owned(req, res); if (!record) return; const index = Number(req.params.chunkIndex); const meta = record.metadata; if (!Number.isInteger(index) || index < 0 || index >= meta.chunk_count) return error(res, 400, "invalid_chunk", "Неверный номер части."); const expected = index === meta.chunk_count - 1 ? meta.expected_size - index * meta.chunk_size : meta.chunk_size; const length = Number(req.get("content-length")); if (!Number.isSafeInteger(length) || length !== expected) return error(res, 400, "invalid_chunk_size", "Размер части не соответствует ожидаемому."); const target = path.join(record.dir, "chunks", String(index)); if (meta.received_chunks.includes(index)) return res.json({ ok: true, duplicate: true }); try { await new Promise((resolve, reject) => { const output = fs.createWriteStream(target, { flags: "wx", mode: 0o600 }); req.on("aborted", () => output.destroy(new Error("aborted"))); req.pipe(output); output.on("finish", resolve); output.on("error", reject); }); const stat = await fsp.stat(target); if (stat.size !== expected) { await fsp.rm(target, { force: true }); return error(res, 400, "invalid_chunk_size", "Часть получена не полностью."); } meta.received_chunks.push(index); meta.received_chunks.sort((a, b) => a - b); meta.status = meta.received_chunks.length === meta.chunk_count ? "uploaded" : "uploading"; await store.save(record.dir, meta); return res.json({ ok: true, received: meta.received_chunks.length, total: meta.chunk_count }); } catch (e) { await fsp.rm(target, { force: true }); return error(res, 500, "chunk_failed", "Не удалось сохранить часть файла."); } }
async function assemble(record) { const out = path.join(record.dir, "source"); const handle = await fsp.open(out, "w", 0o600); try { for (let i = 0; i < record.metadata.chunk_count; i++) { const chunk = path.join(record.dir, "chunks", String(i)); const stat = await fsp.stat(chunk); const expected = i === record.metadata.chunk_count - 1 ? record.metadata.expected_size - i * record.metadata.chunk_size : record.metadata.chunk_size; if (stat.size !== expected) throw new Error("chunk_size_mismatch"); await new Promise((resolve, reject) => fs.createReadStream(chunk).on("error", reject).on("end", resolve).pipe(fs.createWriteStream(null, { fd: handle.fd, start: i * record.metadata.chunk_size, autoClose: false })).on("error", reject)); } } finally { await handle.close(); } const stat = await fsp.stat(out); if (stat.size !== record.metadata.expected_size) throw new Error("assembled_size_mismatch"); return out; }
async function processImage(input, output) { const image = sharp(input, { limitInputPixels: 100000000, failOn: "error" }).rotate(); const metadata = await image.metadata(); if (!["jpeg", "png", "webp"].includes(metadata.format)) throw new Error("unsupported_image"); await image.resize({ width: 2560, height: 2560, fit: "inside", withoutEnlargement: true }).webp({ quality: 85 }).toFile(output); }
async function probe(input) { return new Promise((resolve, reject) => { const child = spawn("ffprobe", ["-v", "error", "-show_entries", "format=format_name:stream=codec_type,codec_name,width,height,pix_fmt", "-of", "json", input], { stdio: ["ignore", "pipe", "pipe"] }); let out = "", err = ""; const timer = setTimeout(() => { child.kill("SIGKILL"); reject(new Error("ffprobe_timeout")); }, 60000); child.stdout.on("data", c => out += c); child.stderr.on("data", c => err += c); child.on("close", code => { clearTimeout(timer); if (code) return reject(new Error("ffprobe_failed:" + err.slice(-500))); try { resolve(JSON.parse(out)); } catch { reject(new Error("ffprobe_invalid")); } }); }); }
async function processVideo(input, output) { const info = await probe(input); const video = (info.streams || []).find(s => s.codec_type === "video"); if (!video || !["h264", "hevc", "vp9", "mpeg4"].includes(video.codec_name)) throw new Error("unsupported_video"); await run("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-i", input, "-map", "0:v:0", "-map", "0:a?", "-vf", "scale='min(1920,iw)':'min(1080,ih)':force_original_aspect_ratio=decrease", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-movflags", "+faststart", output]); }
async function uploadFile(file, filename, mime) { const url = String(process.env.DIRECTUS_URL || "").replace(/\/+$/, "") + "/files"; const form = new FormData(); form.append("file", fs.createReadStream(file), { filename, contentType: mime }); const response = await axios.post(url, form, { headers: { ...form.getHeaders(), Authorization: `Bearer ${process.env.DIRECTUS_TOKEN}` }, maxBodyLength: Infinity, maxContentLength: Infinity, timeout: 30 * 60 * 1000 }); const id = response.data?.data?.id; if (!validId(id)) throw new Error("directus_invalid_file_id"); return id; }
async function removeDirectusFile(id) { try { await directus().client.delete("/files/" + encodeURIComponent(id)); } catch (e) { console.error("media_upload_rollback_file_failed", id, e.message); } }
async function complete(req, res) { const record = await owned(req, res); if (!record) return; const meta = record.metadata; if (meta.status === "completed") return res.json({ ok: true, data: publicMeta(meta) }); if (meta.received_chunks.length !== meta.chunk_count) return error(res, 409, "incomplete", "Загружены не все части файла."); if (active.get(meta.id)?.processing) return error(res, 409, "processing", "Файл уже обрабатывается."); active.set(meta.id, { owner: meta.owner_telegram_id, processing: true }); try { meta.status = "validating"; await store.save(record.dir, meta); const source = await assemble(record); const processedDir = path.join(record.dir, "processed"); await fsp.mkdir(processedDir, { recursive: true, mode: 0o700 }); meta.status = "processing"; await store.save(record.dir, meta); const output = path.join(processedDir, meta.type === "photo" ? "media.webp" : "media.mp4"); if (meta.type === "photo") await processImage(source, output); else await processVideo(source, output); meta.status = "uploading_to_directus"; await store.save(record.dir, meta); const fileId = await uploadFile(output, meta.type === "photo" ? "animal-photo.webp" : "animal-video.mp4", meta.type === "photo" ? "image/webp" : "video/mp4"); meta.directus_file_ids = [fileId]; await store.save(record.dir, meta); const api = directus().client; const current = await api.get("/items/animal_media", { params: { filter: { animal_id: { _eq: meta.animal_id } }, aggregate: { max: "sort" }, limit: 1 } }); const sort = Number(current.data?.data?.[0]?.max?.sort || 0) + 1; meta.status = "creating_record"; await store.save(record.dir, meta); if (meta.is_main) { const old = await api.get("/items/animal_media", { params: { filter: { animal_id: { _eq: meta.animal_id }, is_main: { _eq: true } }, fields: "id", limit: 100 } }); await Promise.all((old.data?.data || []).map(row => api.patch("/items/animal_media/" + row.id, { is_main: false }))); }
    const created = await api.post("/items/animal_media", { animal_id: meta.animal_id, file_id: fileId, type: meta.type, source: meta.source, is_main: meta.is_main, sort }); meta.animal_media_id = created.data?.data?.id; if (!validId(meta.animal_media_id)) throw new Error("animal_media_create_failed"); if (meta.type === "video") { const poster = await generatePosterForMedia(meta.animal_media_id); if (!poster.ok || !validId(poster.posterFileId)) throw new Error("poster_generation_failed"); meta.directus_file_ids.push(poster.posterFileId); } if (meta.is_main) await api.patch("/items/animals/" + meta.animal_id, { main_photo: fileId }); meta.status = "completed"; meta.error = null; await store.save(record.dir, meta); await fsp.rm(record.dir, { recursive: true, force: true }); return res.json({ ok: true, data: { status: "completed", animal_media_id: meta.animal_media_id } });
  } catch (e) { console.error("media_upload_processing_failed", meta.id, e.message); if (!meta.animal_media_id) await Promise.all((meta.directus_file_ids || []).map(removeDirectusFile)); meta.status = "failed"; meta.error = "Не удалось обработать файл. Проверьте формат и повторите попытку."; await store.save(record.dir, meta); return error(res, 422, "processing_failed", meta.error); } finally { active.delete(meta.id); } }
function createMediaUploadRouter() { const router = express.Router(); router.post("/auth", express.json({ limit: "12kb" }), authenticate); router.post("/auth/miniapp", express.json({ limit: "12kb" }), authenticateMiniApp); router.post("/auth/telegram", express.json({ limit: "12kb" }), authenticateWidget); router.get("/auth/telegram/callback", callback); router.get("/session", sessionStatus); router.use(requireSession); router.get("/csrf", token); router.post("/logout", csrf, logout); router.get("/animals", listAnimals); router.post("/init", csrf, express.json({ limit: "16kb" }), init); router.get("/:uploadId/status", status); router.put("/:uploadId/chunks/:chunkIndex", csrf, receiveChunk); router.post("/:uploadId/complete", csrf, complete); router.post("/:uploadId/retry-processing", csrf, complete); return router; }
module.exports = { createMediaUploadRouter, CHUNK_SIZE, MAX_SIZE };
